### ISSUE TITLE
Cant parse the TCB#16F_amang.pdf"

### ISSUE THREAD

**Issue by alphanumericIsNotAvailable** [pagasa-parser/pagasa-parser-web#15]
I am trying your website but I cant parse the TCB#16F_amang.pdf". It shows "Cannot read properties of undefined (reading '0')".

The string is:
"vPk4hp7KHc4pyPbQDHvTOw==:u6DMHp59nZzKM6BW40j9YA4HS6/fqRX4OTYnERUE3iIxVsl+pc6Dfibk99lljxQEskK7TtnDmBuMc4Fklb2SYwGwmBPvH+5qB+1DCZrBU0sWbBdurM1ByKox6eFzrW1ir6NMo+UJ7gEvd2dHehY5U8os15/S/VQKH39s/aBPsT5H3eE7x5Milju7onAbXbkL6ngR9e3sVX1YqRprtRPx8FcZM5vBCwoqYWKTpx5t0dw82truG2OKUX1bah1bbWdXQxBb1vdgMIylBk/WLIVnyno3h43LL1faoQEu8L2iDdxwQ1FXzM6w5Uqc+KDrHJFcffHe2jy5gZqQLpWrbybrSA6GlBR5TT84mynE1ocv0RqQ2I1YTSNqTi3QeSd2qq2GN/wdRhkCr9QetcN6YqYHv27Ro/Wv9SA/L4j3TSRDuRXFdYjuFwK+lo897/O0cLkDusFwd84bimBXeePlQjoySs0+tEm9a83VL65E2qkkPAxYZnCWmimU6YHlW5Ru6UZ8Ooh6HTe1hsIfcYvST4kbWO6mdg4A5dRwVepCAFttT4nRa13JRjHCN4nMT9GJq7rccBa70RlD4NFjIcftH0assVOvi+13V0wfx4c60cboKpenXhCSoIIU4n9VTxSww1Iz9v0biTAyw4qULbo0kO2CgywyIEhaM1g73nAemnkyMpHKmZkgGlwXq7oJCgUdv6erTHxnIHivOAQMOBDLppFqVYvoTdKXjlUTtcbwvBNw2uuQ2B/daRJ/YcAVq0vqqxr3ePdJ7DkCW/l8fakh0KHe1xYBnWpyTTYtqG269yy4JZAtIK1XNX25kIyhF649ujISUALNVdBJYjCG9LfznF1JrlYbjEVcN3a9F1+zMOOD1vuVPdaqr2xy4WRAdBrxyyIHOp3APxUEWA==:C1NFiR3UNI/Ykx3DSed2pA=="

**Comment by ChlodAlejandro** [comment]
Subdependency fixed; changes should hit the website in a few minutes.

**Comment by ChlodAlejandro** [comment]
Fixed. Note that the name is currently garbage; special checks for getting the name of remnant lows haven't been added yet.
![image](https://user-images.githubusercontent.com/12129227/235471816-2ad03a12-3b8a-4977-8577-1b24c5ce1179.png)

**Comment by alphanumericIsNotAvailable** [comment]
I cannot parse pdf again, showing "Cannot read properties of null (reading 'text')"

String:
E/qj3ua7H6lW0QOOtWPJNA==:oAnk0ryc603+6+nm1YUZ6j24xmi2iSgkVAQV5cSdh6Zw41A1S0uO6k8/LCF6qx3dvLHQgtK7VoHcBIUeXu02LCWip4V6FCmdxGGxDw250Gm4cNww/hWTt6KqrGa1m3R4UFx5XPXo8KoVFjIT45cd3pqIvQaG1N9699bIEnmv260U4DJqmjODh7gKGgMbJlTSpMOHjt2mDzQZbjAPtoaIHxgzfhy7nbMglDn5x+55uNfQw4wrAby/4gBpayfi23kLHcH++X1aQo0mXT41vhUi5EQlAEQzuG3VnigOHYOrPTMFDuLHZoYSB3sAkiADAWF4pDzA2t8xsS/3uBrNCcXm2E9dAu0TzXsTmb18oENIhKsJUukh5kimKKKvwpyAE78dtBK+WptgpG0IA1J7Pl3eqYW56L/sS+wl8ew8n7i4BLNi9rLjzsi4KhtYqT7V1tXQR5/XHfFnhZub0CepxmrVsMCnHb8gi7GCcIuIfs/ZQ/ejRiy2qstXxtmTQSwGR0o9/FdoGTsOjFE7K8xMoJNDD0WDlyyIlG/oTgyqsGHQQYGlAOK4XBMlLDBOjqPcwmGeWzFD4dD6tyR7qxM4hyMiH2azcBc8wDOcZKNRtiqmoOA2qi8E2eXXGesKt4qeoWobT7NzmJ42uer//OfqTl91qCIG3t2CBY/689wnFMpfLXamCCVQmwxqaJcy4GMQectzQ0E2gn/F0PJxI/5WtdIMLdiTKJYHUGlfxNgfwxGdcZfYtlrMK/YB4uG04Yg/BlolN1jj3GPO8rsdf4xbPxPZk9ucX6MnDcBHmsLiA3hAfRgqXI0KXFflMONYMvH2dpeLrPjlzbV/qUv7wbQdH6uJAbn2qD7ks2u+26ooq5pV+gV2gqk9aoExfpwdLJrtsSu0EL4=:KUu+jPHRv9aecu9zc+Q1rg==

**Comment by ChlodAlejandro** [comment]
@alphanumericIsNotAvailable Looks like I forgot to deploy v1.2.6, which fixed this issue. Let me know if this still causes problems for you.
